server:
  host: "0.0.0.0"
  port: "6380"
  requirepass: ""

storage:
  shards: 32

gc:
  enabled: true
  interval: "100ms"
  sample_per_shard: 20
  expand_threshold: 0.25

log:
  level: "debug"
  format: "json"

persistence:
  rdb:
    enabled: true
    filename: "dump.rdb"
    interval: "60s"